# Labeler configuration file

# GitHub Actions
github_actions:
  - path: .github/**/*
    labels: ["github_actions"]

# Nutrition Facts
nutrition_facts:
  - path: /nutrition-table-extraction/**/*
    labels: ["nutrition facts"]
  - path: /GSoC2018/**/*
    labels: ["nutrition facts"]

# Documentation
documentation:
  - path: data-sets.md
    labels: ["documentation"]
  - path: README.md
    labels: ["documentation"]

# Datasets
datasets:
  - path: data-sets.md
    labels: ["datasets"]

# Spellcheck
spellcheck:
  - path: spellcheck/**/*
    labels: ["spellcheck"]

# OCR Cleaning
ocr_cleaning:
  - path: ocr_cleaning/**/*
    labels: ["ocr cleaning"]

# Object Detection
object_detection:
  - path: object_detection/**/*
    labels: ["object detection"]

# Logo Annotation
logo_ann:
  - path: logo-ann/**/*
    labels: ["logo-ann"]
  - path: data4good_logo_detection/**/*
    labels: ["logo-ann"]

# Student Projects
student_projects:
  - path: ai-emlyon/**/*
    labels: ["student projects"]

# Language Identification
language_identification:
  - path: language_identification/**/*
    labels: ["language identification"]

# Open Prices
open_prices:
  - path: price-tag-detection/**/*
    labels: ["open prices"]
