github_actions:
  - changed-files:
      - any-glob-to-any-file: .github/**/*

nutrition facts:
  - changed-files:
      - any-glob-to-any-file:
          ["/nutrition-table-extraction/**/*", "/GSoC2018/**/*"]

documentation:
  - changed-files:
      - any-glob-to-any-file: ["data-sets.md", "README.md"]

datasets:
  - changed-files:
      - any-glob-to-any-file: data-sets.md

spellcheck:
  - changed-files:
      - any-glob-to-any-file: spellcheck/**/*

ocr cleaning:
  - changed-files:
      - any-glob-to-any-file: ocr_cleaning/**/*

object detection:
  - changed-files:
      - any-glob-to-any-file: object_detection/**/*

logo-ann:
  - changed-files:
      - any-glob-to-any-file: ["logo-ann/**/*", "data4good_logo_detection/**/*"]

student projects:
  - changed-files:
      - any-glob-to-any-file: ai-emlyon/**/*

language identification:
  - changed-files:
      - any-glob-to-any-file: language_identification/**/*
