[project]
name = "llm-evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.2",
    "deepdiff>=8.6.1",
    "openai>=2.8.1",
    "openfoodfacts>=3.3.0",
    "orjson>=3.11.4",
    "pydantic-ai>=1.22.0",
    "pydantic-evals>=1.22.0",
    "ruamel-yaml>=0.18.16",
]
