[tool.poetry]
name = "spellcheck"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9,<3.10"
openai = "^1.14.3"
evaluate = "^0.4.1"
sacrebleu = "^2.4.1"
rouge-score = "^0.1.2"
nltk = "^3.8.1"
argilla = "^1.26.1"
python-dotenv = "^1.0.1"
datasets = "^2.18.0"
jiwer = "^3.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
