# -*- coding: utf-8 -*-
"""Python-OCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4nCLZFf2gI3VYSD48QGaiqdnIEgp6km
"""

# !pip install pytesseract pillow opencv-python

import cv2
import pytesseract
from PIL import Image

image = '/content/application.jpeg'

image = cv2.imread(image)

# Convert to grayscale (improves accuracy)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

#more optimal
gray = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

# Convert back to PIL image for pytesseract
pil_image = Image.fromarray(gray)

# Run OCR
text = pytesseract.image_to_string(pil_image)

print("Extracted Text:")
print(text)

"""![application.jpeg]

<h1><b>other options<b><h1>
"""

# !pip install easyocr

import easyocr

reader = easyocr.Reader(['en'])

result = reader.readtext('/content/application.jpeg')

for (bbox, text, prob) in result:
  print(f"Detected text: {text} (Confidence: {prob:.2f})")

"""# other **options**"""

# !pip install paddleocr
# !pip install paddlepaddle

from paddleocr import PaddleOCR

ocr = PaddleOCR(use_angle_cls=True, lang='en')

results = ocr.ocr('/content/application.jpeg', cls=True)

for line in results[0]:
    print("Detected text:", line[1][0])



