estimator:
  entry_point: "flan-t5.py"
  source_dir: "scripts/training"
  output_path: "s3://open-food-facts-robotoff/spellcheck/model-training/"
  code_location: "s3://open-food-facts-robotoff/spellcheck/model-training/"
  base_job_name: "flan-t5-training"
  instance_count: 1
  instance_type: "ml.g4dn.xlarge"
  transformers_version: "4.26"                         # the transformers version used in the training job
  pytorch_version: "1.13"                            # the pytorch_version version used in the training job
  py_version: "py39"                                  # the python version used in the training job
  comet_ml_tags: "flan-t5-small"

hyperparameters:
  training_data: "openfoodfacts/spellcheck-dataset"
  evaluation_data: "openfoodfacts/spellcheck-benchmark"
  pretrained_model_name: "google/flan-t5-small"  
  num_train_epochs: 0.01
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  lr: 0.00001
  warmup_steps: 0
  fp16: false
  seed: 42
  generation_max_length: 512
